[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
ego-tree = "0.6.2"
oneshot = "0.1.6"
portable-pty = "0.8.1"
ratatui = "0.26.2"
tui-term = "0.1.11"
